# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

#r:
#- 3.2
#- oldrel
#- devel


matrix:
  include:
    r: release
    #branches:
      #only:
        #- master
    r_packages:
      - tidyverse
      - pkgdown
    after_success: |
      # Rscript -e 'covr::codecov()'
      R CMD INSTALL $PKG_TARBALL
      R -e 'pkgdown::build_site()'
      REMOTE_URL=$(git config --get remote.origin.url)
      cd docs
      git add -A .
      git remote add origin $REMOTE_URL
      git commit -m 'build site'
      git push --force origin HEAD:gh-pages
