# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
#- 3.2
#- oldrel
#- devel


matrix:
  include:
    r: release
    r_packages:
      - tidyverse
      - pkgdown
    after_success: |
      # Rscript -e 'covr::codecov()'
      R CMD INSTALL $PKG_TARBALL
      R -e 'pkgdown::build_site()'
      REMOTE_URL=$(git config --get remote.origin.url)
      git clone $REMOTE_URL -b gh-pages --depth 1 docs
      cd docs
      git add -A .
      git commit -m 'build site'
      git push --force origin gh-pages
