# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - r: release
    after_success:
    - Rscript -e 'remotes::install_cran(c("pkgdown", "tidyverse"))'
    - R CMD INSTALL *tar.gz
    - Rscript -e 'pkgdown::build_site()'
